### ISSUE TITLE
TypeError: addons.find is not a function

### ISSUE THREAD

**Issue by ryangittings** [netlify/netlify-lm-plugin#43]
I'm using Netlify CLI and trying to get large media working. I'm following the instructions, but when running `netlify lm:setup`, I get the following:

```
TypeError: addons.find is not a function
    at provisionService (/.local/share/netlify-cli/node_modules/netlify-lm-plugin/lib/commands/lm/setup.js:88:33)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Task.task (/.local/share/netlify-cli/node_modules/netlify-lm-plugin/lib/commands/lm/setup.js:30:21) {
  context: [Object: null prototype] {}
}
```

I'm using an M1 MacBook Air, `netlify-cli/3.4.5 darwin-arm64 node-v15.5.0`.

**Comment by jeremyzilar** [comment]
Yeah, also on an M1 MacBook, and getting:

```
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=28ddc2cfbbc6e096f48c0e5376db56da
    TypeError: Cannot read property 'slug' of undefined
```

**Comment by erezrokah** [comment]
Hi @ryangittings and @jeremyzilar we're tracking this issue here https://github.com/netlify/cli/issues/514 and working on a solution in https://github.com/netlify/cli/pull/1489.

There is a workaround described in https://github.com/netlify/cli/issues/514#issuecomment-773851791

**Comment by erezrokah** [comment]
Hi all 👋 and sorry for the delay in fixing this.
CLI version [`3.8.0`](https://github.com/netlify/cli/releases/tag/v3.8.0) address this issue.
Please comment if you're still experiencing issues after running:
```
netlify lm:setup
```
